// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090, config = {host: "localhost"});

service / on ep0 {
    resource function get health() returns record {} {
        return {"test": "OK"};
    }

    resource function get voice/name() returns anydata {
        return "";
    }

    resource function post bias\-detection/articles(@http:Payload biasdetection_articles_body[] payload) returns InlineResponse200Ok {
        return {
            body: {biasedArticle: {
                reason: "",
                title: "",
                'type: "positive"
            }}
        };
    }

    resource function post voice/question/formula\-one(http:Request request) returns AnydataOk {
        return {
            body: ""
        };
    }
}
