// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type inline_response_200_biasedArticle record {
    string title;
    "positive"|"negative" 'type;
    string reason;
};

public type InlineResponse200Ok record {|
    *http:Ok;
    inline_response_200 body;
|};

public type AnydataOk record {|
    *http:Ok;
    anydata body;
|};

public type biasdetection_articles_body record {
    string title;
    string content;
};

public type inline_response_200 record {
    inline_response_200_biasedArticle biasedArticle;
};
